[versions]
dokka = "2.0.0"
spotless = "7.0.0.BETA4"
gradleRIO = "2025.1.1"

[libraries]
dokka-java = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokka"}

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
gradleRIO = { id = "edu.wpi.first.GradleRIO", version.ref = "gradleRIO" }
